language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
before_install:
 - sudo add-apt-repository ppa:chris-lea/zeromq -y
 - sudo apt-get update
 - sudo apt-get install -y libpgm-dev libzmq-dev libpq-dev